// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5ZUmS7dsApx1lhwOaBUl8SDoEM5ub4I',
    appId: '1:642470680316:web:fddecfe78c99389615a979',
    messagingSenderId: '642470680316',
    projectId: 'smort-fridge',
    authDomain: 'smort-fridge.firebaseapp.com',
    storageBucket: 'smort-fridge.firebasestorage.app',
    measurementId: 'G-8NPT75WETM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANy4XABNdzpGOZeR-bfvVjrK5qVvWb_LM',
    appId: '1:642470680316:android:745c5b115e990a7115a979',
    messagingSenderId: '642470680316',
    projectId: 'smort-fridge',
    storageBucket: 'smort-fridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfJAbdWxoFx0XlDiS6y5dnzWwgmyvzEM',
    appId: '1:642470680316:ios:c2138b7518489ef615a979',
    messagingSenderId: '642470680316',
    projectId: 'smort-fridge',
    storageBucket: 'smort-fridge.firebasestorage.app',
    iosBundleId: 'com.example.fridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxfJAbdWxoFx0XlDiS6y5dnzWwgmyvzEM',
    appId: '1:642470680316:ios:c2138b7518489ef615a979',
    messagingSenderId: '642470680316',
    projectId: 'smort-fridge',
    storageBucket: 'smort-fridge.firebasestorage.app',
    iosBundleId: 'com.example.fridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW5ZUmS7dsApx1lhwOaBUl8SDoEM5ub4I',
    appId: '1:642470680316:web:bcab236d209018be15a979',
    messagingSenderId: '642470680316',
    projectId: 'smort-fridge',
    authDomain: 'smort-fridge.firebaseapp.com',
    storageBucket: 'smort-fridge.firebasestorage.app',
    measurementId: 'G-3QT85BVLQP',
  );
}
